baseURL: https://www.ellemouton.com
languageCode: en-us
title: Elle Mouton 
theme: "PaperMod"
googleAnalytics: "G-PMLX8P6J9S"
comments: true
enableEmoji: true

menu:
  main:
      - name: Archive
        url: archives
        weight: 5
      - name: Search
        url: search/
        weight: 10

# Needed for search functionality
outputs:
 home:
     - HTML
     - RSS
     - JSON

markup:
  goldmark:
    extensions:
      passthrough:
        delimiters:
          block:
            - - \[
              - \]
            - - $$
              - $$
          inline:
            - - \(
              - \)
            - - $
              - $
        enable: true

params:
  math: true
  comments: true
  defaultTheme: light # auto, dark
  ShowShareButtons: true
  
  homeInfoParams:
        Title: "Mah Brain Nonsense"
        Content: Welcome! Here be Bitcoin & Lightning related things. 

  socialIcons:
      - name: github
        url: "https://github.com/ellemouton"
      - name: twitter
        url: "https://twitter.com/ellemouton"
      - name: keybase
        url: "https://keybase.io/ellemo"
      - name: instagram
        url: "https://www.instagram.com/ellemouton"
      - name: linkedin
        url: "https://www.linkedin.com/in/elle-mouton-50635a143/"
      - name: email
        url: "mailto://elle@lightning.engineering"
      - name: "rss"
        url: "https://www.ellemouton.com/index.xml"

  buttons:
      - name: Archives
        url: archives

  author:
    email: elle.mouton@gmail.com
    name: Elle Mouton
